# Generated by Django 4.1.5 on 2023-01-12 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('STATUS', models.CharField(choices=[('A', 'Active'), ('N', 'Not Active')], max_length=1)),
                ('SOURCE', models.CharField(max_length=100)),
                ('DESTINATION', models.CharField(max_length=100)),
                ('BOOKING_DATE', models.DateField()),
                ('START_DATE', models.DateField()),
                ('END_DATE', models.DateField()),
                ('SECURITY_DEPOSIT', models.IntegerField()),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRST_NAME', models.CharField(max_length=50)),
                ('LAST_NAME', models.CharField(max_length=50)),
                ('OTHER_NAMES', models.CharField(max_length=50)),
                ('NATIONAL_ID', models.CharField(max_length=100)),
                ('ADDRESS', models.CharField(max_length=100)),
                ('EMAIL', models.CharField(max_length=100)),
                ('PHONE_NUMBER', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('STATUS', models.CharField(choices=[('A', 'Active'), ('N', 'Not Active')], max_length=1)),
                ('LICENSE_NO', models.CharField(max_length=50)),
                ('LICENSE_EXPIRY_DATE', models.DateField()),
                ('Custom_User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleetmanagement.customuser')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('STATUS', models.CharField(choices=[('A', 'Active'), ('N', 'Not Active')], max_length=1)),
                ('FIRST_NAME', models.CharField(max_length=50)),
                ('LAST_NAME', models.CharField(max_length=50)),
                ('OTHER_NAMES', models.CharField(max_length=50)),
                ('NATIONAL_ID', models.CharField(max_length=100)),
                ('ADDRESS', models.CharField(max_length=100)),
                ('EMAIL', models.CharField(max_length=100)),
                ('PHONE_NUMBER', models.CharField(max_length=50)),
                ('ROLE', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('STATUS', models.CharField(choices=[('A', 'Active'), ('N', 'Not Active')], max_length=1)),
                ('NAME', models.CharField(max_length=100)),
                ('DESCRIPTION', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('STATUS', models.CharField(choices=[('A', 'Active'), ('N', 'Not Active')], max_length=1)),
                ('NAME', models.CharField(max_length=100)),
                ('DESCRIPTION', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle_Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('STATUS', models.CharField(choices=[('A', 'Active'), ('N', 'Not Active')], max_length=1)),
                ('FIRST_NAME', models.CharField(max_length=50)),
                ('LAST_NAME', models.CharField(max_length=50)),
                ('OTHER_NAMES', models.CharField(max_length=50)),
                ('NATIONAL_ID', models.CharField(max_length=100)),
                ('ADDRESS', models.CharField(max_length=100)),
                ('EMAIL', models.CharField(max_length=100)),
                ('PHONE_NUMBER', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('STATUS', models.CharField(choices=[('A', 'Active'), ('N', 'Not Active')], max_length=1)),
                ('REG_PLATE', models.CharField(max_length=100)),
                ('MAKE', models.CharField(max_length=50)),
                ('COLOR', models.CharField(max_length=50)),
                ('TYPE_OF_BODY', models.CharField(max_length=50)),
                ('CHASIS_NO', models.CharField(max_length=150)),
                ('ENGINE_NO', models.CharField(max_length=150)),
                ('YEAR_OF_MANUFACTURE', models.IntegerField()),
                ('CARRING_CAPACITY', models.CharField(max_length=100)),
                ('FUEL_TYPE', models.CharField(choices=[('PETROL', 'PETROL'), ('DIESEL', 'DIESEL')], max_length=6)),
                ('VEHCILE_TYPE', models.CharField(choices=[('TRUCK', 'TRUCK'), ('CONSTRUCTION', 'CONSTRUCTION')], max_length=12)),
                ('MILLAGE', models.CharField(max_length=100)),
                ('INSUARANCE_EXPIRY_DATE', models.IntegerField()),
                ('COST_PER_KM', models.IntegerField()),
                ('OWNER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetmanagement.vehicle_owner')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tool_issuing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('STATUS', models.CharField(choices=[('A', 'Active'), ('N', 'Not Active')], max_length=1)),
                ('DATE', models.DateField()),
                ('COMMENT', models.TextField()),
                ('DRIVER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetmanagement.driver')),
                ('ISSUING_STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetmanagement.staff')),
                ('TOOL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetmanagement.tool')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('STATUS', models.CharField(choices=[('A', 'Active'), ('N', 'Not Active')], max_length=1)),
                ('REGISTERED_DATE', models.DateField()),
                ('ISSUE', models.TextField()),
                ('VEHICLE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetmanagement.driver')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('STATUS', models.CharField(choices=[('A', 'Active'), ('N', 'Not Active')], max_length=1)),
                ('START_DATE', models.DateField()),
                ('END_DATE', models.DateField()),
                ('SPEEDOMETER_READING_START', models.IntegerField()),
                ('SPPEDOMETER_READING_END', models.IntegerField()),
                ('TOTAL_KMS', models.IntegerField()),
                ('FUEL_CONSUMED', models.IntegerField()),
                ('ENGINE_OIL', models.IntegerField()),
                ('OTHER_OILS', models.IntegerField()),
                ('WEIGHT_CARRIED', models.IntegerField()),
                ('COST', models.IntegerField()),
                ('BOOKING_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetmanagement.booking')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='ALLOCATED_DRIVER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetmanagement.vehicle'),
        ),
        migrations.AddField(
            model_name='booking',
            name='ALLOCATED_STAFF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetmanagement.staff'),
        ),
        migrations.AddField(
            model_name='booking',
            name='PURPOSE_OF_THE_JOURNEY',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetmanagement.task'),
        ),
        migrations.AddField(
            model_name='booking',
            name='VEHICLE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetmanagement.driver'),
        ),
    ]
