# Generated by Django 4.1.5 on 2023-01-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('STATUS', models.CharField(choices=[('A', 'Active'), ('N', 'Not Active')], max_length=1)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('booking_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('security_deposit', models.IntegerField()),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('STATUS', models.CharField(choices=[('A', 'Active'), ('N', 'Not Active')], max_length=1)),
                ('First_name', models.CharField(default=True, max_length=255)),
                ('Last_name', models.CharField(default=True, max_length=255)),
                ('Other_names', models.CharField(default=True, max_length=255)),
                ('national_ID', models.CharField(default=True, max_length=100)),
                ('address', models.CharField(default=True, max_length=100)),
                ('Email', models.CharField(default=True, max_length=100)),
                ('Phone_number', models.CharField(default=True, max_length=255)),
                ('license_no', models.CharField(max_length=255)),
                ('license_expiry_date', models.DateField()),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('STATUS', models.CharField(choices=[('A', 'Active'), ('N', 'Not Active')], max_length=1)),
                ('First_name', models.CharField(default=True, max_length=255)),
                ('Last_name', models.CharField(default=True, max_length=255)),
                ('Other_names', models.CharField(default=True, max_length=255)),
                ('national_ID', models.CharField(default=True, max_length=100)),
                ('address', models.CharField(default=True, max_length=100)),
                ('Email', models.CharField(default=True, max_length=100)),
                ('Phone_number', models.CharField(default=True, max_length=255)),
                ('role', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('STATUS', models.CharField(choices=[('A', 'Active'), ('N', 'Not Active')], max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('STATUS', models.CharField(choices=[('A', 'Active'), ('N', 'Not Active')], max_length=1)),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle_Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('STATUS', models.CharField(choices=[('A', 'Active'), ('N', 'Not Active')], max_length=1)),
                ('First_name', models.CharField(default=True, max_length=255)),
                ('Last_name', models.CharField(default=True, max_length=255)),
                ('Other_names', models.CharField(default=True, max_length=255)),
                ('national_ID', models.CharField(default=True, max_length=100)),
                ('address', models.CharField(default=True, max_length=100)),
                ('Email', models.CharField(default=True, max_length=100)),
                ('Phone_number', models.CharField(default=True, max_length=255)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('STATUS', models.CharField(choices=[('A', 'Active'), ('N', 'Not Active')], max_length=1)),
                ('Reg_plate', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('Type_of_body', models.CharField(max_length=255)),
                ('chasis_no', models.CharField(max_length=150)),
                ('engine_no', models.CharField(max_length=150)),
                ('year_of_manufacture', models.IntegerField()),
                ('carring_capacity', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'PETROL'), ('DIESEL', 'DIESEL')], max_length=6)),
                ('vehicle_type', models.CharField(choices=[('TRUCK', 'TRUCK'), ('CONSTRUCTION', 'CONSTRUCTION')], max_length=12)),
                ('millage', models.CharField(max_length=100)),
                ('insuarance_expiry_date', models.IntegerField()),
                ('cost_per_km', models.IntegerField()),
                ('vehicle_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fleetmanagement.vehicle_owner')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tool_issuing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('STATUS', models.CharField(choices=[('A', 'Active'), ('N', 'Not Active')], max_length=1)),
                ('date', models.DateField()),
                ('comment', models.TextField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetmanagement.driver')),
                ('issuing_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetmanagement.staff')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetmanagement.tool')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('STATUS', models.CharField(choices=[('A', 'Active'), ('N', 'Not Active')], max_length=1)),
                ('Registered_date', models.DateField()),
                ('issue', models.TextField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetmanagement.driver')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('STATUS', models.CharField(choices=[('A', 'Active'), ('N', 'Not Active')], max_length=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('speedometer_reading_start', models.IntegerField()),
                ('speedometer_reading_end', models.IntegerField()),
                ('total_kms', models.IntegerField()),
                ('fuel_consumed', models.IntegerField()),
                ('engine_oil', models.IntegerField()),
                ('other_oils', models.IntegerField()),
                ('weight_carried', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetmanagement.booking')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='allocated_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetmanagement.vehicle'),
        ),
        migrations.AddField(
            model_name='booking',
            name='allocated_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetmanagement.staff'),
        ),
        migrations.AddField(
            model_name='booking',
            name='purpose_of_the_journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetmanagement.task'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetmanagement.driver'),
        ),
    ]
