# Generated by Django 4.1.5 on 2023-01-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='OWNER',
            new_name='VEHICLE_OWNER',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='Custom_User',
        ),
        migrations.AddField(
            model_name='driver',
            name='ADDRESS',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='EMAIL',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='FIRST_NAME',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='driver',
            name='LAST_NAME',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='driver',
            name='NATIONAL_ID',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='OTHER_NAMES',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='driver',
            name='PHONE_NUMBER',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='driver',
            name='LICENSE_NO',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='ADDRESS',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='EMAIL',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='FIRST_NAME',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='LAST_NAME',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='NATIONAL_ID',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='OTHER_NAMES',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='PHONE_NUMBER',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='ROLE',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='COLOR',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='MAKE',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='TYPE_OF_BODY',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle_owner',
            name='ADDRESS',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle_owner',
            name='EMAIL',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle_owner',
            name='FIRST_NAME',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle_owner',
            name='LAST_NAME',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle_owner',
            name='NATIONAL_ID',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle_owner',
            name='OTHER_NAMES',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle_owner',
            name='PHONE_NUMBER',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
