# Generated by Django 4.1.5 on 2023-01-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetmanagement', '0002_remove_booking_status_remove_driver_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Ative', max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Ative', max_length=50),
        ),
        migrations.AlterField(
            model_name='journey',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Ative', max_length=50),
        ),
        migrations.AlterField(
            model_name='repair',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Ative', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Ative', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Ative', max_length=50),
        ),
        migrations.AlterField(
            model_name='tool',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Ative', max_length=50),
        ),
        migrations.AlterField(
            model_name='tool_issuing',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Ative', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Ative', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle_owner',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Ative', max_length=50),
        ),
    ]
